#!/usr/bin/env bash
#loopint through each condition everytime 
for ((i = 1 ; i <=100 ; i++))
do
if [ $((i%5)) -eq 0 ] 
then echo "Buzz" 
elif [ $((i%3)) -eq 0 ] 
then echo "Fizz"
elif [ $((i%15)) -eq 0 ] 
then echo "FizzBuzz"
fi
echo "$i"
done 

