#!/usr/bin/env bash
#same thing with the wile loop but we gonna put a condition using if
i=0
while [ $i -lt 11 ];
do
   if [[ $i -eq 9 ]]; then 
	   echo "Hi";
	else 
		echo "Best School";
   fi
   ((i++))
done 
