#!/usr/bin/env bash
#same thing with the wile loop but we gonna put a condition using if
i=1
while [ $i -le 9 ];
do
   echo "Best School";
   ((i++))
   if [[ $i -eq 9 ]]; then 
	   echo "Hi";
   fi
done 
