#!/usr/bin/env bash
#loops and signles more practice
touch /var/run/myscript.pid
echo "$$" > /var/run/myscript.pid
while true
	do 
	echo "To infinity and beyond"
    sleep 2
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
done
