#!/usr/bin/env bash
#working with loops and & 
if [ $1 == start ] 
if [ $1 == "start" ] 
then 
	./manage_my_process & 
	touch /var/run/my_process.pid
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ $1 == stop ] 
elif [ $1 == "stop" ] 
then
	kill "$(/var/run/my_process.pid)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ $1 == restart ] 
elif [ $1 == "restart" ] 
then 
	kill "$(/var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process & 
	touch /var/run/my_process.pid
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else 
echo "Usage: manage_my_process {start|stop|restart}"
fi

